### ISSUE TITLE
Regex Match Group ($1) Isn't Populating URL As Expected

### ISSUE THREAD

**Issue by Julian88Tex** [requestly/customer-support#100]
After creating a Regex redirect I woudl expect the redirected URL to populate based on what is found with regex patter into $1 as descbied here: https://docs.requestly.io/getting-started/rule-operators#regex-match-operator

Example:
<img width="717" alt="Screen Shot 2021-03-17 at 3 44 21 PM" src="https://user-images.githubusercontent.com/459099/111548290-b84df580-8737-11eb-9290-6bc7253e7a38.png">

But it populates URL with instead:
<img width="388" alt="Screen Shot 2021-03-17 at 3 44 31 PM" src="https://user-images.githubusercontent.com/459099/111548292-b97f2280-8737-11eb-9bc4-31dc0629995a.png">

**Comment by requestly-team** [comment]
Hey @Julian88Tex 
When using regex matching you will have to specify the part of the matched expression you want to use as a variable. This is done by putting that part inside parenthesis.

For eg.
![image](https://user-images.githubusercontent.com/35186614/111601222-2659f180-87f8-11eb-850c-33ed961665a9.png)

Here the brackets indicate that anything after `cat` is the variable and can be used through `$1` in the destination URL. \
So if I search `catfish`, it will take me to  `https://dogfish.com/`

In your case you just have to change the regular expression from `/meet\.google\.com\/\S{12}/ig` to `/(meet\.google\.com\/\S{12})/ig` and it works

> `%241` is just `$1` when URL encoded.
