### ISSUE TITLE
Error 522 both on Firefox and Chrome

### ISSUE THREAD

**Issue by petar-nikov** [requestly/customer-support#102]
This is happening with both browsers is there any way to make the extensions work?

**Comment by requestly-team** [comment]
Hi @petar-nikov, thanks for logging this issue.

Our dashboard website (https://app.requestly.io/) seems reachable to us. 

As with many similar HTTP errors, it is not so easy for us to name the source of the error directly. We would really appreciate if you could give more details about this error, including a screenshot.

Check status: [Is it down right now?](https://www.isitdownrightnow.com/app.requestly.io.html), [Down for everyone or just me?](https://downforeveryoneorjustme.com/app.requestly.io), [Live webpage screenshot](https://screenshot.guru/)

**Comment by petar-nikov** [comment]
@requestly-team thank you for the prompt replay. 
I am providing screenshots from CheckStatus, done from Firefox 86.0.1 (64-bit) on Linux:
- **_Is it down right now:_**
![image](https://user-images.githubusercontent.com/58396791/112428926-9ca0ab80-8d44-11eb-8f3f-0e77e3651e38.png)
- _**Down for Everyone or Just Me**_
![image](https://user-images.githubusercontent.com/58396791/112428974-b215d580-8d44-11eb-9e45-e15eb6c158d5.png)
And from my browser:
![image](https://user-images.githubusercontent.com/58396791/112429403-45e7a180-8d45-11eb-90f1-77aa4b104165.png)

And another one from chrome Version 89.0.4389.90 (Official Build) Arch Linux (64-bit):
![image](https://user-images.githubusercontent.com/58396791/112429660-9a8b1c80-8d45-11eb-9dba-4b5aa72f0393.png)

I've tried to remove the add on from Firefox and reinstall it but #103 prevented me

LMK if I could provide some more info or information

**Comment by requestly-team** [comment]
@petar-nikov Thanks for providing us with the details. 

We have forwarded this issue to the Firebase, our hosting provider. Will keep you posted.

**Comment by petar-nikov** [comment]
@requestly-team Hi, it's still relevant for me. 
Is there any update?
Could I add more info or do something to help this to be resolved?
