### ISSUE TITLE
Requestly throwing javascript error

### ISSUE THREAD

**Issue by srinivasulubv** [requestly/customer-support#105]
After adding new features by the development team of requestly, we can see console errors as shown below.
![Requestly Error](https://user-images.githubusercontent.com/68370448/112798867-60aa6680-9022-11eb-91ee-29c7e2154294.PNG)
Also, the requestly app is no more working, probably I need to switch to different alternative as this behaviour is continuing from since few weeks.

**Comment by requestly-team** [comment]
Hey @srinivasulubv Thank you so much for logging the issue. We will investigate this issue on priority and will keep you posted here.

**Comment by requestly-team** [comment]
@srinivasulubv Are you still facing this issue? We can help you out over a call.

**Comment by srinivasulubv** [comment]
Hi @requestly-team,
I believe some fix has been given to this problem, i couldn't see problem coming any more, marking the problem as resolved. Thanks for a quick resolution, really appreciated.
