### ISSUE TITLE
Does not work with my self-signed certificate

### ISSUE THREAD

**Issue by FrankHarland** [requestly/customer-support#106]
Love the app, but the Chrome plugin just stopped working for me at one point.
I switched to the mac app which provides a bit more feedback:

PROXY_TO_SERVER_REQUEST_ERROR: Error: self signed certificate

I'm using a self-signed certificate for my development environment. Is there any way i can still get Requestly to work?

**Comment by requestly-team** [comment]
Hey @FrankHarland Thank you so much for logging this issue. As part of Requestly Installation we do install a custom CA which signs the requests proxied by Requestly proxy server. https://docs.requestly.io/desktop-app/how-to...#certificates

Did you modify/remove the Requestly CA from your keychain by any chance?

**Comment by FrankHarland** [comment]
Hi @requestly-team ,

I did not remove or modify the cert:
![image](https://user-images.githubusercontent.com/31548701/113107624-6f507380-9204-11eb-8f9b-8fe84a6b9899.png)

But i am using a second (self-signed) certificate for my local development, so I'm guessing this might be the issue
![image](https://user-images.githubusercontent.com/31548701/113107906-bb031d00-9204-11eb-8d3c-0a5369c43674.png)
