### ISSUE TITLE
Temporarily unable to access files

### ISSUE THREAD

**Issue by erkesado** [requestly/customer-support#107]
Hello,

My script files on Requestly have been inaccessible for 7 to 20 minutes several times for the last 12 hours. They give 502 error on Google Firebase Storage.
Why does it happen regularly for the last 12 hours?
It hurts my online business.

Yours sincerely,
Erdenebat Oyungerel

**Comment by requestly-team** [comment]
Hey @erkesado 

Thank you for reaching out. We checked Firebase Storage Status - https://status.firebase.google.com/ and there's no outage mentioned there. 

Have you faced the similar issue in the past or is this the only instance you faced this issue?

**Comment by erkesado** [comment]
It is the first time I am facing this issue.
I have never encountered this issue on Requestly before.

**Comment by requestly-team** [comment]
@erkesado What's the size of the JS Code you have? We can think of better reliable alternative if this is business critical for you.

**Comment by erkesado** [comment]
There are 3 small files. First one is 3Kb, second one is 2Kb and the last one is 18Kb.
I moved them to Google Drive and the issue is gone.

Thanks for your concern,
Erdenebat Oyungerel

**Comment by requestly-team** [comment]
Thanks @erkesado for the response! We will keep an eye on this 502 issue from Firebase. Glad that you are able to resolve the issue for you. Can we close this issue?
