### ISSUE TITLE
unable to save 

### ISSUE THREAD

**Issue by rahulprasadgupta** [requestly/customer-support#108]
while using unable to save

**Comment by shaili123** [comment]
+1, Unable to create new rule or edit an existing one

**Comment by dzienisz** [comment]
wtf? shouldn't it be local only? where our data goes?

**Comment by patrykskrzymowskirepository** [comment]
+1, reinstall did not help.

**Comment by requestly-team** [comment]
Apologies for the inconvenience caused. The issue has been fixed. You should be able to create new rules now.
Thank you for reaching out.

**Comment by requestly-team** [comment]
@dzienisz Your rules are saved locally or synced by Google only, depending upon your account settings [here](https://app.requestly.io/settings). As of now, we don't store your rules on our servers. We are soon coming up with a Wordpress plugin and a Cloudflare app, which might require this though.

**Comment by requestly-team** [comment]
Closing this issue for now, more info about the incident can be found here on our LinkedIn post [here](https://www.linkedin.com/posts/requestly_in-our-latest-deployment-about-2-hours-ago-activity-6793228035974848512-scwb).
