### ISSUE TITLE
Cache busting helpers

### ISSUE THREAD

**Issue by sprynm** [requestly/customer-support#109]
Hello,
I use this tool to inject a cache busting query string.  But I have to manually update the value  on each refresh.  It would be handy to have a short code to inject a random number.  A time stamp rounded to seconds || hours || days would work well.

Or is there something I missed in the current set up? 

![image](https://user-images.githubusercontent.com/4483296/116473470-0d4b5400-a82c-11eb-9e46-dc58b8ff2fa8.png)

**Comment by requestly-team** [comment]
Hey @sprynm Thank you for reaching out. Requestly has list of predefined functions which can be used to provide dynamic value in the value fields in the rules.

Here's the detailed [StackOverflow Answer on how you can use Requestly to cache burst requests](https://stackoverflow.com/a/63966511/816213) - https://stackoverflow.com/a/63966511/816213

In short, you can use `rq_rand(4)` as the value. This will be replaced by 4 digit random number at the runtime.
