### ISSUE TITLE
no http PATCH method in filters

### ISSUE THREAD

**Issue by guai** [requestly/customer-support#110]
pls add http PATCH method to filters

**Comment by guai** [comment]
bot go away

**Comment by theinfin8y** [comment]
@nafees87n Can we please check if this is doable and webRequest request details supports PATCH?

**Comment by nafees87n** [comment]
@guai Support for PATCH method has been added to filters. It is live now.

**Comment by guai** [comment]
@nafees87n thats cool, thanks
