### ISSUE TITLE
Change the Default Dictionary in Adobe Acrobat Reader

### ISSUE THREAD

**Issue by requestly-team** [requestly/customer-support#111]
I saw [your post on Medium](https://requestly.medium.com/change-the-default-dictionary-in-adobe-acrobat-reader-86090c7f016) regarding the subject line. I've installed the Requestly extension and tried to change the destination to Merriam-Webster, rather than the multilingual dictionary in the post's example, but get stuck. After the rule is added, Acrobat's Look Up redirects to the M-W homepage but I can't figure out how to make it execute the search.

Any advice? A lot of word nerds would love to be able to do this.

**Comment by requestly-team** [comment]
Can you please share the rule you have created? Follow these steps

1. Select the rule
2. Click on Share the rule

Share the link here and we will investigate what's not working for you.

**Comment by DaveM-BC** [comment]
https://app.requestly.io/rules/#sharedList/1620134632080

**Comment by nafees87n** [comment]
@DaveM-BC You can find the same rule at our [marketplace](https://app.requestly.io/marketplace). You can use rules from the marketplace without any limitations. 
Visit- https://app.requestly.io/marketplace

**Comment by requestly-team** [comment]
@DaveM-BC You can find the same rule on our [marketplace](https://app.requestly.io/marketplace). You can use rules from the marketplace without any limitation.
Visit- https://app.requestly.io/marketplace

**Comment by DaveM-BC** [comment]
> @DaveM-BC You can find the same rule on our [marketplace](https://app.requestly.io/marketplace). You can use rules from the marketplace without any limitation.
> Visit- https://app.requestly.io/marketplace

I clicked "on" for the M-W rule in the marketplace, but the result is the same. Look Up opens the M-W home page, but doesn't execute the search.

Tried it again with my adblocker disabled on the M-W site, same outcome.

**Comment by requestly-team** [comment]
> > @DaveM-BC You can find the same rule on our [marketplace](https://app.requestly.io/marketplace). You can use rules from the marketplace without any limitation.
> > Visit- https://app.requestly.io/marketplace
> 
> I clicked "on" for the M-W rule in the marketplace, but the result is the same. Look Up opens the M-W home page, but doesn't execute the search.
> 
> Tried it again with my adblocker disabled on the M-W site, same outcome.

Did you turn off the rule previously made by you? Please turn it off and then try the M-W rule in marketplace. Do let us know the outcome.

**Comment by DaveM-BC** [comment]
> > > @DaveM-BC You can find the same rule on our [marketplace](https://app.requestly.io/marketplace). You can use rules from the marketplace without any limitation.
> > > Visit- https://app.requestly.io/marketplace
> > 
> > 
> > I clicked "on" for the M-W rule in the marketplace, but the result is the same. Look Up opens the M-W home page, but doesn't execute the search.
> > Tried it again with my adblocker disabled on the M-W site, same outcome.
> 
> Did you turn off the rule previously made by you? Please turn it off and then try the M-W rule in marketplace. Do let us know the outcome.

That did it! Thank you.

**Comment by requestly-team** [comment]
@DaveM-BC Can you. please rate us on the Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en? Can we close this ticket?

**Comment by DaveM-BC** [comment]
> @DaveM-BC Can you. please rate us on the Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en? Can we close this ticket?

Yes and yes.

**Comment by requestly-team** [comment]
Thank you @DaveM-BC. Would really appreciate your review on Chrome Store. Feel free to reach out if you have any issue. Closing this.
