### ISSUE TITLE
Subscription Sign-Up Address Issue

### ISSUE THREAD

**Issue by zpyoung** [requestly/customer-support#112]
When purchasing a new premium subscription, every field in the address needs a value prior to allowing a purchase. This has 2 problems:

1. Most addresses in the US do not have an address line 2 (I had to just use a "dash" symbol)
2. The error message raised simply indicates that an address needs to be added prior to purchase. It does not tell you which field has the error nor is an error raised when "saving" the address. 

While not critical, this does make it difficult to upgrade. Many people would simply stop trying.

**Comment by requestly-team** [comment]
Hey @zpyoung, Thanks for your detailed feedback. We'll act upon this really soon.

Meanwhile feel free to reach us at [contact@requestly.io](mailto:contact@requestly.io) in case you face any difficulty with the subscription or the app in general.
