### ISSUE TITLE
Replace a substring in URL while keeping rest of the URL same

### ISSUE THREAD

**Issue by sufumin** [requestly/customer-support#113]
Hello, I like this software, I've read this page but still have some problems.
(https://docs.requestly.io/using-rules/replace-rule)

if I want to
Turn 
① https://www.test.com/flle-xxxx.html
(xxxx is a number)
Into 
② https://www.test.com/down-xxxx.html
(② xxxx is the same as ① xxxx)

Example 1:
Turn 
https://www.test.com/flle-123456.html
Into 
https://www.test.com/down-123456.html

Example 2:
Turn
https://www.test.com/flle-654321.html
Into
https://www.test.com/down-654321.html

How can I do this?
Thanks.

**Comment by requestly-team** [comment]
@sufumin How about this

```
Replace www.test.com/file-
With www.test.com/down-

When URL contains www.test.com
```

Can you try this at your end once and let us know if it solves your problem?

**Comment by sufumin** [comment]
It works! Thanks. Have a nice day!  :) :)
