### ISSUE TITLE
rules are not saved

### ISSUE THREAD

**Issue by dzienisz** [requestly/customer-support#114]
in case where you have 6 pair in rule data are not saved even when info bar say it is

**Comment by requestly-team** [comment]
Hey @dzienisz Thanks for logging the issue. Can you please. share more information about your rule? Which rule type was it?

**Comment by dzienisz** [comment]
Header rule

in some cases I don't know exactly when data are not saved

**Comment by requestly-team** [comment]
Hey @dzienisz 

Can we jump on a call quick to look into this together? This looks like account specific. Please select a slot here - https://calendly.com/requestlyio/30min and we will be in touch & resolve this issue.

Best
- Sagar, CTO & Co-Founder

**Comment by requestly-team** [comment]
Resolved this offline! Hence closing this issue.
