### ISSUE TITLE
Rules page stuck on getting started.

### ISSUE THREAD

**Issue by telakk** [requestly/customer-support#116]
When in the rules page requestly only shows getting started even though the extension is installed. I click the chrome link and chrome shows it installed.
![image](https://user-images.githubusercontent.com/85236500/120487556-1035e900-c384-11eb-988b-1d35e2bde3cd.png)
If I click the extension button at the top requestly is also recognizing that the extension is installed.
![image](https://user-images.githubusercontent.com/85236500/120487820-483d2c00-c384-11eb-9a89-a59da8573c4b.png)

**Comment by requestly-team** [comment]
@telakk 
It is most likely that the extension doesn't have the required permissions. You can visit [chrome://extensions](chrome://extensions) and give Requestly Extension the access on all sites. Also, you can refer to our troubleshooting documentation [here](https://docs.requestly.io/troubleshooting) to know about this.

![image (17)](https://user-images.githubusercontent.com/35186614/120669264-ea583380-c4ac-11eb-8174-35c6bf45ee44.png)

Let us know if you face any problem.

**Comment by requestly-team** [comment]
Hey @telakk, Did you manage to solve this issue? Did above solution work out?
