### ISSUE TITLE
Insert script does not work on index

### ISSUE THREAD

**Issue by MikkelSVDK** [requestly/customer-support#117]
I'm running a Raspberry Pi Zero with Chromium Version 86.0.4240.197 (Official Build) Built on Raspbian

I have a insert script rule that doesn't work with the: if URL contains https://example.com.
When i visits the site, it does not load the scripts and i don't see any errors.

**Comment by requestly-team** [comment]
Hey @MikkelSVDK Thanks for logging this issue. We have never tested Requestly on Raspbian. Do you know if Raspbian supports Chrome extensions? Did you install Requestly directly from Chrome Store?

**Comment by MikkelSVDK** [comment]
Hello,
Requestly does work on a Raspberry pi. The rule becomes active as soon as i leave the root. i also tried to create a modify header rule to see if it was a problem with the website, but it did work on every page within the scope. 
It was installed it via the Chrome store

**Comment by requestly-team** [comment]
Hey @MikkelSVDK Apologies for the delay in response. Do you mean to say that Modify headers rule is working fine but Script rule is not. Can you please share the rule with us here? 

Also, Can you please open the Chrome Devtools console and help us with any errors you see there?
