### ISSUE TITLE
Can't control order of rules

### ISSUE THREAD

**Issue by jpaddock** [requestly/customer-support#120]
I have a redirect rule that I want to run first followed by query param rule.  This isn't possible and it makes the tool less useful as I need to update the query string of a redirected url to have a random number on it.

**Comment by requestly-team** [comment]
Hey @jpaddock You can use the random number function in the Redirect rule too. 

Here's an article which explains how can we add a random query parameter - https://dev.to/requestlyio/disable-caching-of-particular-js-css-file-2k82. Although, this article is in context of Query Params Rule but the same concept can be used with Redirect Rule too.

So, in short this is that you can try. In the Redirect Rule

```
Source Url Contains <yourdomain.com>
Destination https://<newdomain.com>?randomparam=rq_rand(4)
```

Please try this once. If this doesn't work, can you please share your rule with us. You can follow this guide to share the rule with us - https://docs.requestly.io/managing-rules/sharing

**Comment by jpaddock** [comment]
Oh, that worked perfectly!!! Thank you so much.

**Comment by requestly-team** [comment]
Hey @jpaddock Thanks you so much for confirming. We're glad that solution worked out for you. Can you please help us with a review on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
