### ISSUE TITLE
Modify using JavaScript

### ISSUE THREAD

**Issue by doggy8088** [requestly/customer-support#125]
Is there any docs for the args when modify using JavaScript? I have no clue how to modify the response and there is no docs for that. I also doubted about how to debugging. I can't console.log any message.

```js
function modifyResponse(args) {
  const {method, url, response, responseType, requestHeaders, requestData} = args;
  // Change response below depending upon request attributes received in args
  
  return response;
}
```

**Comment by lazyvab** [comment]
@doggy8088 The extension currently supports modifying response only for AJAX requests invoked using [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest). Support for [fetch](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) API should be coming soon.

Example for modifying response using Javascript:
Suppose you want to set `message` property in response JSON according to one of the request headers `x-env`. You can do something like:
```js
function modifyResponse(args) {
  const { responseText, requestHeaders } = args;
  const environment = requestHeaders['x-env'];
  const responseJson = JSON.parse(responseText);
  responseJson.message +=
    environment === 'prod' ? 'You are in production environment' : 'You are in non-production environment';
  return JSON.stringify(responseJson);
}
```

**Comment by doggy8088** [comment]
@lazyvab I see. I do expected to see if you can support writing JavaScript to modify any HTTP requests.

**Comment by edeustace** [comment]
Hi - I know this issue is closed - but does requestly support `fetch` now?

**Comment by nafees87n** [comment]
@edeustace Yes, you can also modify requests using `fetch`.
Please find the documentation [here](https://docs.requestly.com/general/http-rules/rule-types/modify-response-body).
