### ISSUE TITLE
I have a replace host rule, but it's not doing anything.

### ISSUE THREAD

**Issue by ansorensen** [requestly/customer-support#126]
My rule is supposed to replace resource files from a local URL to a remote one. Specifically, it replaces the host and port:

localhost:9000

I'm using a filter of .js and .css files.

However, in the console when I try to load a page that requests JS/CSS assets from localhost, I still get errors like:

GET http://localhost:9000/content/css/SuperSelect.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:9000/content/js/SuperSelect.js net::ERR_ABORTED 404 (Not Found)
 

Indicating that no replacement is happening. I've double-checked that my rule is enabled. I've tried refreshing the page and restarting the Chrome browser I'm using. Still the same error.

**Comment by Infin8y** [comment]
Hey @ansorensen Thanks for reaching out. Can you please help us with the rule which you have created.

Here is a guide on how you can share a rule with us - https://requestly.io/blog/2018/06/14/share-rules-with-other-users/

**Comment by ansorensen** [comment]
https://app.requestly.io/rules/#sharedList/1625491851258-Rules-that-don't-work

**Comment by ansorensen** [comment]
Yes, I did have it on. I turned it off when it did nothing and I had to
find another way to reroute requests.

**Comment by ansorensen** [comment]
I'm not using the extension at the moment, and don't plan to.

**Comment by Infin8y** [comment]
Hey @ansorensen We are sad to hear this! Do you mind telling me how did you solve this problem? 

Can you please try once again after removing the filters? Looks like there is an issue with filters, we'd investigate further and solve it asap.

**Comment by ansorensen** [comment]
Not really, I don't have the server set up and I'm using a different tool
now.

**Comment by Infin8y** [comment]
Could you tell us which tool did you switch to?

**Comment by ansorensen** [comment]
Acrylic DNS proxy
