### ISSUE TITLE
Mac icon is corrupted at small sizes

### ISSUE THREAD

**Issue by mikehdt** [requestly/customer-support#129]
![Screen Shot 2021-07-27 at 11 30 55 am](https://user-images.githubusercontent.com/4432939/127080551-a1ddb517-0af1-44b3-9c5a-c6f99a01f0ce.png)

When using the Requestly desktop app, the icon appears to be corrupted at small sizes. It's okay at larger sizes. This is with 0.0.7 on MacOS 10.15.7

**Comment by theinfin8y** [comment]
Hey @mikehdt Thank you for logging this. We will fix this in our upcoming desktop app release.

**Comment by theinfin8y** [comment]
@mikehdt We have recently made a lot of changes in our desktop app. We have also fixed this in the latest version. Can you please check again at your end?
