### ISSUE TITLE
Unable to save file when user has 5 files

### ISSUE THREAD

**Issue by alonhartman** [requestly/customer-support#130]
When a user has 5 files (and is in the free plan) he should be able to do updates in the 5 files he has.
When trying to update 1 of the files, the message "It's time to upgrade" appears and the changes cannot be saved.

Steps to reproduce:

1. login with a free plan user
2. upload or create 5 files
3. open 1 of the files and edit it
4. click on the "Save" button

Actual result: the "It's time to upgrade" message appears even the user is allowed to have 5 files in the free plan

Expected result: the user should be able to have and edit all of his 5 files according to the free plan

![Screen Shot 2021-08-17 at 8 11 36](https://user-images.githubusercontent.com/11316700/129667218-4fb03590-8163-4275-a780-db062fc4bc1b.png)

**Comment by sagarsoni7** [comment]
Hey @alonhartman 

Thanks for reporting this issue. We'll fix this within next few hours

**Comment by sagarsoni7** [comment]
@alonhartman - We have updated the web app. 

Can you please confirm if this has been resolved?

**Comment by alonhartman** [comment]
Yes, it works fine now.
Thank you :)
