### ISSUE TITLE
Can't add a second rule

### ISSUE THREAD

**Issue by pedr0-fr** [requestly/customer-support#134]
Just made a fresh install of chrome and installed the requestly extension. When I click "+ New Rule" nothing happens and I see the following error in the console:

![Screenshot from 2021-09-08 23-29-59](https://user-images.githubusercontent.com/16596928/132594421-2b51e968-4f50-4751-a6c3-570e023b602a.png)

This is my second rule, it worked fine when I created the first rule.

**Comment by theinfin8y** [comment]
Hey @pedr0-fr thanks for submitting the issue to us. Does the problem persist when you refresh the page? Can you also tell us your browser version & name? We will try to reproduce this at our end?

Can you also tell us if you tinkered with data anyway?

**Comment by sagarsoni7** [comment]
@pedr0-fr - We have made some changes at our end.

Can you please refresh the page and recheck?

**Comment by pedr0-fr** [comment]
now it works, thanks!

**Comment by theinfin8y** [comment]
Thank you @pedr0-fr for confirming! Can I request you to rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa
