### ISSUE TITLE
Remote Rule

### ISSUE THREAD

**Issue by Harfho** [requestly/customer-support#135]
How does the remote Rule works?
is it like shared rule ?

**Comment by sagarsoni7** [comment]
@Harfho - Not exactly,  you provide an end-point from where Requestly will periodically import the rules

**Comment by sagarsoni7** [comment]
@Harfho - I just activated trial on your account. Login with your email h_____7@gmail.com and open

**Comment by Harfho** [comment]
> @Harfho - I just activated trial on your account. Login with your email [h_____7@gmail.com](mailto:h_____7@gmail.com) and open
> 
> https://app.requestly.io/settings/remote-rules

Thanks for the trial activation 
so if I paste a link like https://app.requestly.io/shared-lists/viewer/1623908770341-6-17-2021 where and how will I see those rule are in action / working

**Comment by sagarsoni7** [comment]
@Harfho - The link you posted is of a shared list, this will not work with Remote Rules. Remote Rules feature is used to fetch Rules periodically from an **external** server. 

So for example if my server endpoint is https://mywebsite.com/requestlyRules and response (json) is 

```
[
  {
    "creationDate": 1631535360601,
    "description": "",
    "groupId": "",
    "id": "Cancel_zg49o",
    "isSample": false,
    "modificationDate": 1631535369111,
    "name": "Test Remote",
    "objectType": "rule",
    "pairs": [
      {
        "id": "2rnzl",
        "source": {
          "filters": {},
          "key": "Url",
          "operator": "Contains",
          "value": "facebook.com"
        }
      }
    ],
    "ruleType": "Cancel",
    "status": "Inactive"
  }
]
```

I'll configure it like this:

<img width="1680" alt="Screenshot 2021-09-13 at 6 04 20 PM" src="https://user-images.githubusercontent.com/29792913/133084362-b38a6ce3-e39a-47e2-8bfc-4228bac3ec48.png">

Then Requestly will call your endpoint periodically (in background), fetch the rules and will place them in a special group called Remote Server Rules. You will see this group in your list of rules.

<img width="1680" alt="Screenshot 2021-09-13 at 6 07 18 PM" src="https://user-images.githubusercontent.com/29792913/133084725-302e26dc-fe6d-48b7-a7c1-2ab133a0cbc2.png">

Let me know if this is of any help.

**Comment by Harfho** [comment]
> @Harfho - The link you posted is of a shared list, this will not work with Remote Rules. Remote Rules feature is used to fetch Rules periodically from an **external** server.
> 
> So for example if my server endpoint is https://mywebsite.com/requestlyRules and response (json) is
> 
> ```
> [
>   {
>     "creationDate": 1631535360601,
>     "description": "",
>     "groupId": "",
>     "id": "Cancel_zg49o",
>     "isSample": false,
>     "modificationDate": 1631535369111,
>     "name": "Test Remote",
>     "objectType": "rule",
>     "pairs": [
>       {
>         "id": "2rnzl",
>         "source": {
>           "filters": {},
>           "key": "Url",
>           "operator": "Contains",
>           "value": "facebook.com"
>         }
>       }
>     ],
>     "ruleType": "Cancel",
>     "status": "Inactive"
>   }
> ]
> ```
> 
> I'll configure it like this:
> 
> <img alt="Screenshot 2021-09-13 at 6 04 20 PM" width="1680" src="https://user-images.githubusercontent.com/29792913/133084362-b38a6ce3-e39a-47e2-8bfc-4228bac3ec48.png">
> 
> Then Requestly will call your endpoint periodically (in background), fetch the rules and will place them in a special group called Remote Server Rules. You will see this group in your list of rules.
> 
> <img alt="Screenshot 2021-09-13 at 6 07 18 PM" width="1680" src="https://user-images.githubusercontent.com/29792913/133084725-302e26dc-fe6d-48b7-a7c1-2ab133a0cbc2.png">
> 
> Let me know if this is of any help.

It helps me and clarify so much. Now I understand how it works + Its a powerful future.

**Comment by sagarsoni7** [comment]
@Harfho - Glad it helped

Can I request you to rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa

**Comment by Harfho** [comment]
> @Harfho - Glad it helped
> 
> Can I request you to rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa

No problem , Kindly let the Rule Sync/Downlead immediately the first time it was import
