### ISSUE TITLE
Add "Authorization" header instead of default "authorization"

### ISSUE THREAD

**Issue by sashadev-sky** [requestly/customer-support#139]
For example, to add a bearer token. This seems to no longer be possible but was at some point.

**Comment by sashadev-sky** [comment]
Nevermind its the same thing! had the group set on "off" which just turned it off event though it was individually on "on"

**Comment by sagarsoni7** [comment]
@sashadev-sky - yeah that's a bit confusing. We'll be revamping the table soon
