### ISSUE TITLE
Doubled slashes in URL

### ISSUE THREAD

**Issue by AlbertoP64** [requestly/customer-support#14]
Hi, problem is, along with corrected edit, I get duplicated slashes where they aren't supposed to be.
The nice thing is the browser ignores it, so this is not as urgent, but I wished to signal the bug anyway.

I have set that rule (to edit language of MSDN / DOC Microsoft pages):
Replace Host or some part of URL
Pairs
Replace	`/it-it/`
  With	`/en-us/`
Source  Url   Contains   `.microsoft.com/`

While getting correctly edited url, I get also slashes duplicated anywhere on that url:
Source URL:
`https://docs.microsoft.com/it-it/dotnet/standard/choosing-core-framework-server`
Edited URL:
`https://docs.microsoft.com//en-us//dotnet/standard/choosing-core-framework-server`
I think the bug is reproducible.

**Comment by sachinjain024** [comment]
Hi @AlbertoP64 

Thanks for logging the issue. Actually, with your Replace-With pair, our system is identifying it as regex and replacing the regex it-it with /en-us/ so you are getting double slashes.

Instead you can try this:

    Replace it-it/
    With en-us/
    Url contains .microsoft.com/

When user specifies anything between two slashes we treat it as regex like /ssss/. For more information read [Replace Rule Documentation](https://www.requestly.in/content/documentation/replace-rule/#pattern-matching-in-replace-rule)

**Comment by AlbertoP64** [comment]
Ok tanks for prompt reply :).

1) I prefer to match initial slash also, to avoid editing wrong URL part.
Good new is, Regex Escape sequence is also supported:
I entered \/it\-it\/ into the search part, and double slashes disappeared.
My fault, I was only totally unaware that regexp was active (not reading ALL the docs) :-P.

2) To make very clear to user that regexp is available, and let it control WHEN to use it
(so to avoid syntax glitches when user doesn't mean to use),
I will humbly suggest to add a 'Regexp enabled' Checkbox in the UI
 for each search / replace pair row.

Is it something you could approve?
Need to open another issue for the proposal?
Regards

**Comment by sachinjain024** [comment]
Thanks @AlbertoP64 for the suggestion. Currently we infer regex from user string if it is a regex or not and that I do by checking if given string is present between two slashes and then if there is any flag like `i` or `g`.

You are completely correct about this user experience. I will try to fix this in our upcoming releases.

Thanks for the explanation.

**Comment by AlbertoP64** [comment]
I am very sorry, but seems I spoke too soon.... :grimacing: was not carefully looking in.

Sadly happens that my supposed workaround with Regexp Escape... doesn't work at all!
Mistakenly I was checking only for double // slashed disappearing,
 but not carefully looking and not seing that language bit was NO MORE edited from URL.....
 so my string change was really ineffective as it do inhibit the extension from operating.

I've done some other test, and, at the very moment,
the only working thing is your suggestion
to remove beginning slash, that I've done.

Sorry to say the issue must be considered still open :expressionless:
Awaiting for next release to fix this :smirk:

**Comment by sachinjain024** [comment]
@AlbertoP64 No problem. We can keep it open and I will try to fix this in upcoming release.
I am wondering about this suggestion

    Replace: docs.microsoft.com/it-it/
    With: docs.microsoft.com/en-us/

What's the problem with this approach ?
