### ISSUE TITLE
Requestly does not work with Safari browser

### ISSUE THREAD

**Issue by Anyclip** [requestly/customer-support#141]
Installed Requestly-0.0.12-beta.dmg on MacOS v11.6 and Requestly does not work with Mac Safari v15.0.  I was able to install Requestly successfully on the Mac however when I apply my Requestly rules they do not work.  The same Requestly rules work however in other browsers (Windows Chrome, Edge, Firefox).  Who can help me with this issue?

**Comment by Anyclip** [comment]
> @Anyclip - Thanks for logging this issue. I'll help you resolve this immediately.
> 
> Actually to use Requestly with Safari, we need to set the system proxy to the server that is being run by Requestly.
> 
> We'll automate this in coming weeks but for now please refer to this guide: [requestly.io/for-safari/](https://requestly.io/for-safari/)
> 
> Overall, you need to set the proxy settings and also install the Certificate (else HTTPS website won’t load)
> 
> Screenshots are also provided in the guide.
> 
> In case you face any difficulty, we can also connect over a quick Zoom call and I'll help you set up Requestly for Safari. (Send me Hi at [contact@requestly.io](mailto:contact@requestly.io))

Thanks for your prompt response.  Thanks to your valuable assistance I was able to enable Requestly to work on Mac Safari however it only appears to be working for one of my Requestly rules.  When I attempt to use different Requestly rules that always work on Mac Chrome using the Requestly Chrome extension the same rules do not work when I disable the Chrome extension and instead use Requestly-0.0.12-beta.  Any idea why?  Possible solution for this?

**Comment by sagarsoni7** [comment]
@Anyclip - I am trying to resolve that CORS error, will get back to you real soon
