### ISSUE TITLE
Redirect - Equals, Regex, Wildcard does not work on Chrome

### ISSUE THREAD

**Issue by sdfr19-8rhqeufbnqnef** [requestly/customer-support#143]
Hi,

The redirect feature of requestly only works for 'contains'. It does not work for equals or either of the matches.

I am trying to redirect youtube.com to https://www.youtube.com/feed/subscriptions and even if you get this to work using the requestly contains rule, youtube for some reason will then say you are offline when trying to play a video.

**Comment by sdfr19-8rhqeufbnqnef** [comment]
Thank you. I have just sent $10.

I know it’s not going to change the world, but I really appreciate your help and I really appreciate your redirect extension which has allowed me to redirect Youtube.

Thanks again. 😊

Ben

**Comment by theinfin8y** [comment]
@sdfr19-8rhqeufbnqnef Your feedback about Requestly is gold for us. Yes, It makes a whole lot of difference in our lives.  Thank you so much for being so kind!

Never hesitate to reach out to us anytime.
