### ISSUE TITLE
Block an URL: filter by HTTP method

### ISSUE THREAD

**Issue by keul** [requestly/customer-support#145]
Currently "Block an URL" requestly configuration are limited to URL/HOST/PATH check, while it would be useful to add a filter based on HTTP method used.

A good example: if I block an URL for "http://myapp.com/foo/bar" it will also block CORS attempts (HTTP OPTIONS), while I'd like to block only HTTP POSTs.

**Comment by sagarsoni7** [comment]
@keul - If you're using Requestly extension for Chrome, we have an option to add such a filter. Can you please check if it serves your purpose? Else we would explore

<img width="1080" alt="Screenshot 2021-11-06 at 2 15 59 PM" src="https://user-images.githubusercontent.com/29792913/140603791-e92267d2-0cba-40bc-b688-8716d778c372.png">
<img width="1080" alt="Screenshot 2021-11-06 at 2 17 34 PM" src="https://user-images.githubusercontent.com/29792913/140603810-13fed163-838e-48c3-9457-04adba8801d4.png">


If you're using Requestly Desktop app instead, we are yet to add support for filters there.

**Comment by keul** [comment]
Wops! I totally missed the filter icons! 🤦 

Thanks

**Comment by theinfin8y** [comment]
Thanks @keul - Glad we could help. Would you like to join our Slack group for faster support?
