### ISSUE TITLE
aircanada.com breaks when Requestly is installed (even with 0 rules and no other configuration)

### ISSUE THREAD

**Issue by ArgonAlex** [requestly/customer-support#147]
Just having the Requestly extension enabled in Chrome causes aircanada.com to not load properly. As in much of the page content is clearly not loading and/or not interactive. Disabling the extension completely resolves the issue.

It looks like their website makes extensive use of a service worker. Does Requstly cause issues with that?

I can reproduce in Chrome on Mac and Windows devices.

**Comment by theinfin8y** [comment]
Hey @ArgonAlex! Thanks for logging this issue. I acknowledge this issue and I am able to reproduce this. Started investigating, will keep you posted here.

**Comment by sagarsoni7** [comment]
@ArgonAlex While we look into this issue, you can try our [desktop app](https://requestly.io/desktop/) and open chrome from there. aircanada.com is loading fine

**Comment by theinfin8y** [comment]
Hey @ArgonAlex 

We have made the changes in the codebase. It will require us to release the latest build on chrome store. We will upload it tomorrow and let you know it is approved and available in chrome store.

**Comment by theinfin8y** [comment]
@ArgonAlex We have uploaded the latest build in Chrome Store & Edge Store. It is pending for review from their side. Once Google & Microsoft team approves, it will be available for general public. I will keep you posted here.

**Comment by theinfin8y** [comment]
Hey @ArgonAlex The latest version is available in Chrome Store. This should be fixed for you now. Can u please try again and let me know if this works for you.

**Comment by theinfin8y** [comment]
Hey @ArgonAlex The latest version is available in Microsoft Edge too & other places. Can you please confirm if the issue is resolved for you. We'd close the ticket then.

**Comment by ArgonAlex** [comment]
Thanks for fixing quickly and providing detailed updates! It looks good now.

**Comment by theinfin8y** [comment]
Thanks @ArgonAlex for the response. Glad I could help. Can I request you to rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-modify-headers/mdnleldcmiljblolnjhpnblkcekpdkpa
