### ISSUE TITLE
Add to existing header?

### ISSUE THREAD

**Issue by SunflowerFuchs** [requestly/customer-support#32]
Is there a way to add on to an existing header, e.g. add an entry to the cookie header? 
I've tried the modify header rule, but couldn't seem to make it work.

**Comment by sachinjain024** [comment]
@egoisticalgoat This is currently not possible if you do not already know the original value of the header. I take this as a feature request and will let you know when this is available.

**Comment by egoisticalgoat** [comment]
Thanks for the quick response! I'm looking forward to it :+1:

**Comment by joshuabradley012** [comment]
I would love to see this as well. Fantastic plugin by the way.

**Comment by sachinjain024** [comment]
@joshuabradley012 Can you give me some examples of what do you want to add into the header value? Apart from cookie header, does this make sense for any other header too ?

**Comment by requestly-team** [comment]
Closing this ticket due to lack of response. Feel free to reopen to start discussion on this.
