### ISSUE TITLE
[FR] Variable support

### ISSUE THREAD

**Issue by caviyacht** [requestly/customer-support#41]
It would be nice to have the ability to possibly create key/value pairs of variables somewhere to be used in the regex conditions.  Has this been considered before?

There are many times when I want my requestly rules to work on the same set of hosts every time.  Creating a variable with the regex for these hosts and using it on each new rule would make it easier to maintain and add new hosts to all existing rules.

I don't know how this would work, maybe the variable has the same type of drop-down that the request match has to define what type of variable it is, then on the requestly rule a new option exists in the drop-down to select a variable?

**Comment by sachinjain024** [comment]
@caviyacht Thanks for logging the issue. This is a great feature add. We have added this to our roadmap and will implement in future

Thanks again for suggesting a nice feature. Keep them coming.
