### ISSUE TITLE
Allow cookies to be set/mapped to headers or URL parameter

### ISSUE THREAD

**Issue by andreventuravale** [requestly/customer-support#43]
I would like to request a feature where you can ask a specific cookie value to be set/mapped to a request header or to a URL parameter.

Example:

Given I have cookie FOO=BAR
When a request is made
Then append a "&foo=bar" parameter to related request URL

Given I have cookie FOO=BAR
When a request is made
Then drop a HTTP request header into related request as "x-foo: BAR"

**Comment by andreventuravale** [comment]
This is useful for development environments which could replicate some production behaviors which has such habilities, like Akamai servers.

**Comment by sachinjain024** [comment]
@andreventuravale Thanks for the feature request. We really appreciate it. 

We have got tons of feature in the queue right now. We have added this to our roadmap. We will think about how to provide a solution for such use cases in the future.

Is this something blocking you?

**Comment by andreventuravale** [comment]
@sachinjain024 thanks for the quick response, no it is not blocking me at all, just a nice to have feature.
