### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by VDMummaneni** [requestly/customer-support#44]
It would be nice to have a functionality where users can move the requests up and down based on their use. 
Right now when a user has multiple requests, its difficult to navigate and search through all the requests. 
If there is a way we could just move the requests based on the usage , it would be great

**Comment by sachinjain024** [comment]
@VDMummaneni We have recently finished "Grouping" feature. Using Groups you can manage your rules, create a group for a logical set of rules which should be toggled on/off together. Or maybe a use case of "Archive". We are planning to release that soon. Hopefully, that solves your use case.

We will support searching and filtering soon. Thanks for your feedback.
