### ISSUE TITLE
Making Default Action Enable/Disable

### ISSUE THREAD

**Issue by sreevisakh** [requestly/customer-support#46]
While working I have to activate and deactivate the plugin frequently. Can you make the Left Click in the extension Icon to Activate/Deactivate the plugin rather than opening the requestly page. Which can be opened via an options menu in the right click context menu.

**Comment by sachinjain024** [comment]
Thanks! @sreevisakh for reaching out with a nice suggestion. I think the frequency of opening requestly page is much higher than activating and deactivating the plugin and this is why we open the requestly page on left click on extension icon. Click on the extension icon is very intuitive too and this is why I don't want to change this behavior.

When we released the activate/deactivate feature we provided this in right-click context menu but many users complained and we removed it from there.

**Comment by requestly-team** [comment]
@sreevisakh This is an older issue but I guess we have a couple of solutions to improve the experience here.

1. User can mark certain rules as favourite (Notice the heart icon in Rule row) and the rule can be toggled from Requestly Popup. No need to enable disable the entire extension.
2. User can do right click on extension icon and do deactivate/activate from there.

Can we close this ticket now?
