### ISSUE TITLE
user agent change

### ISSUE THREAD

**Issue by rtmcrc** [requestly/customer-support#47]
On user agent change the "platform" "os_name" and "os_flavor" are not substituted so the web site knows that user agent is fake

**Comment by rtmcrc** [comment]
Hi, select user agent with different OS than yours and check its state on http://f.vision antidetect test website. Proceed with "Start advanced test" button after page loads and there you may see if user agent is substituted properly.

**Comment by sachinjain024** [comment]
Thanks @rtmcrc for providing more information. We debugged into this issue and user agent is correctly set by Requestly. However, there is a code in the page which makes an ajax call to this URL (http://f.vision/index.php/json_passive_ports) and as a response of this we get

```
{
  os_flavor: "7 or 8",
  os_match_q: 0,
  os_name: "Windows"
}
```

And this again overrides the user agent. You may try to block this request using Requestly Cancel Rule and check if it works for you.

Thanks
- Requestly Team

**Comment by requestly-team** [comment]
@rtmcrc Can we close this ticket?

**Comment by rtmcrc** [comment]
> @rtmcrc Can we close this ticket?

yes, thank you

**Comment by requestly-team** [comment]
Thanks a lot, @rtmcrc. Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
