### ISSUE TITLE
[FR] Inject HTML/CSS

### ISSUE THREAD

**Issue by caviyacht** [requestly/customer-support#49]
I don't know if this is in the road-map currently, but it would be nice to be able to inject HTML/CSS as we can already with JavaScript.

I am currently using another extension that is very old and has never been updated to do this and would like to get rid of it and just use requestly.

Here is what is currently being used.  It works a little like requestly, but really meant for injecting markup/css/js into a page.  https://chrome.google.com/webstore/detail/web-override/lllllobkincmdnjfkbknjacacmnlajll

Things that would make a requestly version better is the option of where to inject the CSS instead of how web override does it.

**Comment by sachinjain024** [comment]
Thanks, @caviyacht for the feature request. This is indeed in roadmap. We will keep you posted here when this feature will be available.

Justin, would you be available for quick talk about Requestly since you are using it from long time. My skype id is sachinjain024.

**Comment by requestly-team** [comment]
@caviyacht Apologies, We forgot to update you. We added the support for CSS almost an year back. Check this screenshot

<img width="1064" alt="Screenshot 2020-02-19 07 27 13" src="https://user-images.githubusercontent.com/35186614/74794469-4e231100-52e9-11ea-941d-eca611771593.png">

Adding support for HTML is quite tricky and is not being asked by many people. Therefore we kinda kept it in backlog. We can choose to work on that based on requirements from our users.

**Comment by requestly-team** [comment]
@caviyacht Closing this ticket. Feel free to reopen if you have any questions/concerns.
