### ISSUE TITLE
[feature request] Keyboard shortcut

### ISSUE THREAD

**Issue by l4nd0r** [requestly/customer-support#50]
Hi..
Thaks for the cool plugin.
One thing i am missing is the possibility to switch the user agent with a (configurable) shortcut.
Would be nice to be able to configure a shortcut for a defined useragent. If you press the button you switch the UA to something and create a rule for that website implicit.

Thank You

**Comment by sachinjain024** [comment]
Hi @rolandg 

Thanks for opening the ticket. This is indeed in roadmap but we have planned this feature to be part of features under premium subscription.

**Comment by rolandg** [comment]
good to know. 
Thanks
