### ISSUE TITLE
Sharing Rule Doesn't Working

### ISSUE THREAD

**Issue by yasinguzel** [requestly/customer-support#51]

**Comment by yasinguzel** [comment]
Step to produce:

- Open insert script rule.
- Share rule and get the link.
- Open link in another chrome user.

Then rule does not work. I tried to open the same rule in another chrome user. That worked.

**Comment by requestly-team** [comment]
Apologies @yasinguzel for missing out on this. You can share rules with users who have Requestly installed. If you try to open Shared Link with a user who doesn't have Requestly, it won't open. We are going to enhance that functionality in the near future. Was that case with you?

**Comment by requestly-team** [comment]
@yasinguzel We are closing this issue for now. If you are still facing this, feel free to reopen.
