### ISSUE TITLE
Add current date as query param in a page URL

### ISSUE THREAD

**Issue by requestly-team** [requestly/customer-support#57]
Every day I need to access an URL that contains the current date (report).
Can I add this dynamic value in URL?

https://business.facebook.com/adsmanager/manage/campaigns?attribution_windows=default&date=2020-02-01_2020-03-04&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS

Parameter "date" is a range. I need to replace the end date with current date:

Ex.: If I run today (Mar 25) ➜ date=2020-02-01_2020-03-25

**Comment by requestly-team** [comment]
Hey Eduardo,

You can use [Insert Script feature](https://medium.com/requestly-docs/inserting-scripts-dynamically-in-a-webpage-be4af90da20a) to write a small snippet which manipulates the date query param and updates the end date as today's date.

Here's the snippet you have to use on business.facebook.com

```
const url = window.location.href,
      searchParams = new URLSearchParams(url),
      d = searchParams.get('date');

if (d) {
	const d1 = d.split('_')[0],
      today = (new Date()).toISOString().split('T')[0],
      newDateParam = [d1,today].join('_');

	window.location.href = url.replace(d, newDateParam);
}
```

Here's long story short. We have created the rule for you. Please follow these steps -
1. Open https://app.requestly.in/rules
2. Login from the SideRail
3. Open https://app.requestly.in/rules/#sharedList/1585232826940-facebook-business-date-range
4. Click on Import List

You will get the rule! Try opening your business.facebook.com page as usual and let us know if you face any issues.

**Comment by scheduardo** [comment]
Tks.

The end date has changed to Mar 23. Today is 26. Why?

Regards,

**Comment by requestly-team** [comment]
Hey @scheduardo Can you please share the page URL which you opened and the URL which you got. Since we don't have a facebook business account, it is difficult to try it out at our end.

**Comment by requestly-team** [comment]
For Example - We just opened

https://business.facebook.com/?attribution_windows=default&date=2020-02-01_2020-03-04&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS

And It redirected successfully to

https://business.facebook.com/?attribution_windows=default&date=2020-02-01_2020-03-26&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS

**Note** Intentionally removed /adsmanager/manage/campaigns so it actually does redirect we have created and not go to signin page.

**Comment by scheduardo** [comment]
The current page is:

https://business.facebook.com/adsmanager/manage/campaigns?act=1&business_id=2&attribution_windows=default&column_preset=2858463370842840&date=2020-02-01_2020-03-04&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS-STRING_SET%1EIN%1E[%22active%22%2C%22deleted%22%2C%22inactive%22%2C%22off%22%2C%22pending%22]%1Dcampaign.impressions-NUMBER%1EGREATER_THAN%1E%220%22%1DSEARCH_BY_CAMPAIGN_GROUP_NAME-STRING%1ECONTAIN%1E%22PLG-T2%22&time_breakdown=days_1&sort=name~1

Here it is changing to:

&date=2020-02-01_**2020-03-23**

**Comment by requestly-team** [comment]
Hey @scheduardo

What happens If you manually change the date in above mentioned URL to &date=2020-02-01_2020-03-27. Does facebook allow it?

Just open the below link directly. I have changed the end date to 2020-03-27 below.

https://business.facebook.com/adsmanager/manage/campaigns?act=1&business_id=2&attribution_windows=default&column_preset=2858463370842840&date=2020-02-01_2020-03-27&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS-STRING_SET%1EIN%1E[%22active%22%2C%22deleted%22%2C%22inactive%22%2C%22off%22%2C%22pending%22]%1Dcampaign.impressions-NUMBER%1EGREATER_THAN%1E%220%22%1DSEARCH_BY_CAMPAIGN_GROUP_NAME-STRING%1ECONTAIN%1E%22PLG-T2%22&time_breakdown=days_1&sort=name~1

I just want to see if facebook allows it or not?

Best
Requestly Team

**Comment by scheduardo** [comment]
Yes. I can do it:

See https://www.screencast.com/t/3JAoqyzPBAD

**Comment by requestly-team** [comment]
Thanks @scheduardo for the link. I have made some fixes in the script.
Please import the rule again from this link - https://app.requestly.in/rules/#sharedList/1585323648791-facebook-business-v2

And try again. Here's the summary of change made in the script
- Try to change the param after 2second of page load instead of before page load
- Check if URL already has the latest date as end date then do not make redirect

Please try it once and let us know if that makes any difference at your end. We have tested on example.com and https://business.facebook.com/?attribution_windows=default&date=2020-02-01_2020-03-24&filter_set=CAMPAIGN_GROUP_DELIVERY_STATUS

It looks to work fine.

**Comment by scheduardo** [comment]
GREAT!

Now it's working.

Tks a lot!

--
Eduardo Schurtz


Em sex., 27 de mar. de 2020 às 12:44, Requestly Team <
notifications@github.com> escreveu:

**Comment by requestly-team** [comment]
Awesome! @scheduardo Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
