### ISSUE TITLE
file: to https:

### ISSUE THREAD

**Issue by raymondlowe** [requestly/customer-support#59]
How to use it to change or redirect a url like "file://www.google.com" to "https://www.google.com"

In some situations when I open a HTML file from my c: drive that has links to "//www.google.com" they get turned into "file://www.google.com" and so this fails which makes it hard to tell if the page is ok.  If I could just take all URLs with "file:" and turn that into "https:" it would allow testing more easily.

**Comment by requestly-team** [comment]
Thanks @raymondlowe for logging an issue. File protocols are tricky. We are working with our engg team to figure out if there can be solution using [Replace Rule](https://docs.requestly.io/docs/using-rules/replace-rule/)

**Comment by requestly-team** [comment]
Hey @raymondlowe 

We explored how to achieve this use case. This is possible using Requestly but require slight changes in our permissions.

Right now, we can't redirect `file://` URLs because we haven't specified permission to intercept file based URLs.

We have made the changes now. We will upload the build to Chrome store in the next 1-2 days but Chrome team typically takes 3-4 weeks to review the release usually.

Amongst covid situation they might take longer. Anyways, we will keep you posted.

Thanks
Requestly Team

**Comment by requestly-team** [comment]
Closing this ticket due to inactivity.

**Comment by KenyeeC** [comment]
I update to the latest version, but it doesn't change from file: to https:

**Comment by lazyvab** [comment]
@KenyeeC I created a very simple rule:

```
Rule Type: Replace String Rule
Replace "file://" with "https://"
If URL contains "" (empty string) to intercept all requests.
```

When I opened "file://example.com" in browser, it rather opened "https://example.com".

Can I have a look on your rule definition?

**Comment by KenyeeC** [comment]
> https://

I use the chrome extension

**Comment by KenyeeC** [comment]
> @KenyeeC I created a very simple rule:
> 
> ```
> Rule Type: Replace String Rule
> Replace "file://" with "https://"
> If URL contains "" (empty string) to intercept all requests.
> ```
> 
> When I opened "file://example.com" in browser, it rather opened "https://example.com".
> 
> Can I have a look on your rule definition?
![image](https://user-images.githubusercontent.com/18223471/192773492-e97db3c0-ada9-457d-945d-397e5700b3e6.png)

**Comment by KenyeeC** [comment]
> @KenyeeC I created a very simple rule:
> 
> ```
> Rule Type: Replace String Rule
> Replace "file://" with "https://"
> If URL contains "" (empty string) to intercept all requests.
> ```
> 
> When I opened "file://example.com" in browser, it rather opened "https://example.com".
> 
> Can I have a look on your rule definition?

I use the chrome extension, and it seems to work. But in browser it dosen't work
![image](https://user-images.githubusercontent.com/18223471/192774171-f2ae1703-666e-4367-aac1-9e27ad3953f3.png)
![image](https://user-images.githubusercontent.com/18223471/192774203-15b1693d-8e98-4512-a0ee-37a369868276.png)

**Comment by lazyvab** [comment]
@KenyeeC Your rule definition looks good. And I have the same rule setup on my machine which works very well.
Btw, is your rule Active? The toggle before "Share Rule" button seems disabled.

**Comment by KenyeeC** [comment]
@lazyvab I open it but still not working. My chrome version is 105.0.5195.125 (x86_64)

![image](https://user-images.githubusercontent.com/18223471/192779478-8e4a9cda-d24f-4100-a372-cc471d6e6b9b.png)

![image](https://user-images.githubusercontent.com/18223471/192779741-573c8cb4-10d4-4376-b3a3-a92b9e817554.png)

**Comment by KenyeeC** [comment]
> My chrome version is 105.0.5195.125 (x86_64)

And I try to download Edge and use requestly, the same rule is still not working
