### ISSUE TITLE
Where are rules stored?

### ISSUE THREAD

**Issue by carpii** [requestly/customer-support#60]
Could you clarify where Requestly rules are actually stored please?

Are they just stored locally in my extension (and then Chrome itself syncs them to other machines via my Google account).

Or are rules always stored on Requestly servers, and so each of my machines logs in and downloads them from there?

**Comment by requestly-team** [comment]
Hey @carpii 

By default, all rules are stored in Chrome Local Storage and If you login into Chrome on multiple devices these rules are synced to other devices by Google Sync Service.

As of today, Rules are not stored on Requestly Servers.

However, When you share a list of rules with other users then those rules are stored on our servers and we generate a link for those rules which can be shared with other users. 

You have the full control to delete the link as well which hard deletes the rules from our servers too.

Here are some references
- https://requestly.io/privacy-policy/
- https://docs.requestly.io/docs/managing-rules/share-rules/share-rules/

Cheers!
Team Requestly

**Comment by carpii** [comment]
@requestly-team Thanks guys!
