### ISSUE TITLE
Import not working properly

### ISSUE THREAD

**Issue by hFire24** [requestly/customer-support#62]
I exported a requestly file and modified it. When I tried to import it, the import will delete itself probably due to errors. Is there a way to find out why the requestly export won't import? It's kind of like the errors someone would get when compiling Java code.

**Comment by requestly-team** [comment]
Hi @hFire24,

Although we highly recommend modifying rules through dashboard only, if you really want to modify the exported file, please ensure that object structure and constraints aren't affected. 

For example, some keys like "value" can accept only strings starting with "http:" or "https" when the "operator"  is set to "Equals".

Currently, there is no way to log such errors during import but we have added this to our bucket list and you may expect an update soon.

If you require any further information, feel free to ask.

Thanks,
Requestly Team
