### ISSUE TITLE
custom script character limitation

### ISSUE THREAD

**Issue by alonhartman** [requestly/customer-support#63]
Hi,
First, please let me just say that your add-on is amazing and is so helpful in my work.
I have a question/enhancement:
Sometimes I need to inject scripts which may reach even more than 1000 characters, so I'd like to know if there is an option to expand the character count limitation from 500 to more than that?

Thanks a lot,
Alon.

**Comment by requestly-team** [comment]
Hey @alonhartman We are so glad to know that you love Requestly. A happy user is the most precious asset for any product.

Actually, we store the rules locally in the Chrome Storage and chrome storage has constraints on the size of an object. Therefore, we had to restrict it to 500 characters.

Here's an alternative you can try
1. Use Requestly Library - https://app.requestly.io/library/ to create your JS, CSS or JSON Files
2. Here's an example file we created in Requestly Library - https://goo.gl/cr8VZ6
3. Here's a JSBin in which we used the JS File hosted in Requestly Library - https://jsbin.com/ciqonogibu/edit?html,console,output

Please let us know if this works for you.

**Comment by requestly-team** [comment]
hey @alonhartman 

Did you get a chance to look at the proposed solution? We are now planning to store the scripts given by user to be uploaded in the library anyways and hence this 500 characters limit thing will be gone soon.

**Comment by alonhartman** [comment]
Hi,
Sorry for the late response.
Using the Requestly Library is not a good option for me because my rule contains 2 parts.
1. A URL for a script located on my Companys' amazon S3 bucket and this script is updated all the time
2. A set of configurations for the script to work by (overriding some of the default configurations given in the script) - This is the part where the limitation really bothers my work.

Since I need the script to update automatically (upon every release of it), the Requestly Library is not a good solution for me because then I'll have to manually download the new script and integrate the relevant settings into it upon every release of the script or per every change of configuration I need (which is something that is being done at least twice a day.

I think that the best solution currently for me now is to wait until you'll store the scripts given by the user in the library automatically.

Thank you for the great product and for the response.
Alon

**Comment by requestly-team** [comment]
@alonhartman Can you use the JS uploaded on your company's S3 URL directly inside the script rule ? So Instead of using Custom Code section, start using JS URL and use S3 URL?

**Comment by alonhartman** [comment]
Hi,
Thanks for the quick reply.
Maybe I didn't explain my issue the best way so, please let me clarify.

I do use the uploaded js file from the S3 but since it's a script which can use different configurations (there's a set of default configurations defined in the script) and I need to change the configurations almost every time I use it, I have built a rule that looks like the attached screenshot.
<img width="1176" alt="requestlyExample" src="https://user-images.githubusercontent.com/11316700/98154164-07a82d80-1edd-11eb-8236-b7570d243e0a.png">

1. In the first part of the rule, I define the relevant configuration I need to use.
2. In the second part of the rule, I refer to the script located in the S3 bucket.

The problem I have is whenever the configuration I need to define exceeds the 500 chars.

Thanks,
Alon.

**Comment by requestly-team** [comment]
Hey @alonhartman,

Thank you so much for explaining this. I have one question/doubt based on your previous statement

> Since I need the script to update automatically (upon every release of it), the Requestly Library is not a good solution for me because then I'll have to manually download the new script and integrate the relevant settings into it upon every release of the script or per every change of configuration I need (which is something that is being done at least twice a day.

If you use Requestly Library and create the JS file in Library for just the configuration part, then it should solve your problem. So the Idea is like you said, you will include two JS Files in one script rule as shown in the screenshot above

1. Create a JS File in Requestly Library for the configuration and you can keep editing configuration directly in Library Editor and Include in the Script rule
2. Include JS from your company's S3 in the same rule

We ensure that the scripts are executed in order. Do you see any problem with this approach?
