### ISSUE TITLE
How to get Modify header to work with Redirect request?

### ISSUE THREAD

**Issue by LDY681** [requestly/customer-support#66]
Hi, I am trying to replace an image on a website with my own.
However, this action was blocked due to CORS policy. 
So what I tried to do is add a response header which set Access-Control-Allow-Origin to *. 
However, it still seems to not work. The error is still: 
Access to image at 'https://www.otherwebsite.com/replaceImage.png' (redirected from 'https://www.originalwebsite.com/originalImage.jpg') from origin 'https://www.originalwebsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
I have attached to rules.
[redirect request.txt](https://github.com/requestly/customer-support/files/4839161/redirect.request.txt)
[add response header.txt](https://github.com/requestly/customer-support/files/4839162/add.response.header.txt)

Can you have a look please? 
Thanks!

**Comment by requestly-team** [comment]
Thanks @LDY681 for providing the details. We are looking into it.

**Comment by requestly-team** [comment]
Hey @LDY681 

You should update your Modify Header Rule to work on the new URL (destination URL mentioned in the Redirect Rule) instead of the Source URL.

So your header rule should look something like this

```
Add -> Response Header -> Access-Control-Allow-Origin -> *
Url -> Contains ->  https://web.sanguosha.com
```

Can you please try this and let us know if this works for you?

**Comment by LDY681** [comment]
Do you mean Url -> Contains ->  https://avos-cloud-gwibfiplqh86.s3.amazonaws.com because that would be my destination URL in the Redirect Rule (redirect request.txt).

**Comment by LDY681** [comment]
I just changed to my destination URL and now it's working! Thank you for your help!

**Comment by requestly-team** [comment]
@LDY681 Glad we could help. Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
