### ISSUE TITLE
Files stored at requestly.page.link can't be inserted to the page.

### ISSUE THREAD

**Issue by CubikNeRubik** [requestly/customer-support#68]
Hi,
I have an insert rule that inject file stored at your side.
Before link was in format `https://requestly.page.link/<some hash>`
Now when I try to open it I get a redirect to `https://firebasestorage.googleapis.com/<some params>`

Now all insert rules that use old link format get error 
![image](https://user-images.githubusercontent.com/15522719/90116260-e8768580-dd5d-11ea-8341-cafa116e9ada.png)

And everything is work with new links. Problems that it is hard to update all my rules because I have more then 100 rules

I understand that this is probably impossible to update all my rules automatically from your side
So can you at least make button Copy URL at File tab to return link in new format instead of old?

**Comment by requestly-team** [comment]
Thank you @CubikNeRubik for logging this issue. Our team is looking at it and working on the solution. Will keep you posted.

**Comment by requestly-team** [comment]
Hey @CubikNeRubik, We used Firebase service for generating the shortened links and they have started to create an issue now. We are reaching out to Firebase to help with a permanent resolution. Also, we are exploring if there is anything which we can do from our side. In the meantime, can you please try this interim fix.

Here is the sharedList - https://app.requestly.io/rules/#sharedList/1597397269766-Insert-Script-Rule-Temp-Fix
Import this list and let us know if it works for you.

**Comment by CubikNeRubik** [comment]
Hey @requestly-team 
Thanks for the fast reaction. Hotfix works well

Waiting for a general solution)

**Comment by CubikNeRubik** [comment]
^

**Comment by CubikNeRubik** [comment]
Hey @requestly-team are you going to fix this issue?

**Comment by requestly-team** [comment]
Hey @CubikNeRubik We investigated into this. The link generator service which we used from Firebase has been deprecated. We have already stopped generating the links by this service so you won't face any issues with the new links.
