### ISSUE TITLE
Unable to open zikanalytics in Iframe

### ISSUE THREAD

**Issue by requestly-team** [requestly/customer-support#69]
Query from User

```
Hello is there a way to user this to for example get this website into an iframe with the chrome extension? like aliexpress.com
Thanks it appears to have worked for most of them I just cant get this one working zikanalytics.com
I dont think it does anything elaborate as a standard iframe chrome extension allows it to work
```

![image](https://user-images.githubusercontent.com/35186614/92323469-a12a9e80-f056-11ea-8067-077064e80c28.png)

**Comment by requestly-team** [comment]
Thanks for submitting the issue. We investigated zikanalytics.com and it is using another response header content-security-policy like this

```
content-security-policy: frame-ancestors vimeo.com youtube.com facebook.com google.com manychat.com intercom.io intercomcdn.com
```

So In order to open https://www.zikanalytics.com in Iframe you also need to remove this header, here is the rule which we created

https://app.requestly.io/rules/#sharedList/1599386953133-iframe-buster

You can try to open this after importing above rule - https://jsbin.com/vaseyacera/edit?html,output

**Comment by requestly-team** [comment]
Here's a screenshot showing zikanalytics.com in an Iframe using Requestly Modify Headers rule

![image](https://user-images.githubusercontent.com/35186614/92323558-6412dc00-f057-11ea-8f08-dc0c44e18962.png)

**Comment by jayfinley** [comment]
Thanks

This loads website fine, but I am unable to login to the site using iframe.

Once I enter login details the screen hangs like its trying to login but never completes.

Are there any further steps needed?

**Comment by requestly-team** [comment]
Hey @jayfinley! We investigated into this problem. There are a few issues we found with this site

The Site is sending SameSite=Lax; Secure as set-cookie in the response header. Read more about it.

Right now, Requestly provides functionality to modify the headers but it requires much more control over cookies. It requires you to modify the existing value of cookie and specify SameSite=None; secure in the cookie value

Right now, LAX is preventing the setting of cookie. Read more about it here - https://web.dev/samesite-cookies-explained/

I am afraid in order to achieve this use case, you would either need to write some custom code or find another chrome extension with advanced cookie modification capabilities.

**Comment by jayfinley** [comment]
Thanks any suggestions to do this

would something like this in conjunction with Requestly achieve it?

https://chrome.google.com/webstore/detail/cookie-editor/iphcomljdfghbkdcfndaijbokpgddeno?hl=en

**Comment by requestly-team** [comment]
Hey @jayfinley Cookie Editor doesn't work because Cookie Editor allows to modify already set cookie or set cookies. But the requirement here is modify cookie on the fly something like Requestly does.

As I mentioned above, we need to remove SameSite=Lax and change it to SameSite=None. Unfortunately, we don't have the capability to replace something in the header value which is needed in this case.

**Comment by jayfinley** [comment]
OK any chance this will ever be a feature of Requestly?

If sites decided to use the same method Iframes would stop working for login side.

Thanks for your help :-)

**Comment by requestly-team** [comment]
@jayfinley This is not a very common use case. We have added this in our roadmap but we are not very sure if we will plan this in near future. 

Can we close this ticket or is there anything else on which you need assistance?
