### ISSUE TITLE
Two Broken Links in Website

### ISSUE THREAD

**Issue by KarenEfereyan** [requestly/customer-support#70]
Hello team @requestly-team . I found two broken links in the [requestly website](https://requestly.io/)
![requestly](https://user-images.githubusercontent.com/56835876/93744919-84f83700-fbea-11ea-967b-4e59e094d746.png)
Please look into it as soon as possible. Nice work on this project by the way

**Comment by sachinjain024** [comment]
Thanks, @KarenEfereyan for logging this. We will fix this soon.

**Comment by KarenEfereyan** [comment]
> Thanks, @KarenEfereyan for logging this. We will fix this soon.

**Comment by KarenEfereyan** [comment]
Okay Sanchin. Well done by the way
