### ISSUE TITLE
X-Frame For Ebay

### ISSUE THREAD

**Issue by jayfinley** [requestly/customer-support#72]
Hello

Is there anyway to embed ebay.com /co.uk into an X-Frame?

I am able to access the page with a basic remove but am unable to login without error messages.

Thanks :-)

**Comment by requestly-team** [comment]
Hi @jayfinley !

Thanks for opening the issue. Many websites prevent to be loaded via third party site frame of an X-Frame.

Here's what you can try:

- Removing `X-Frame-Options` header 
- Modifying `set-cookie` header to enable third party cookies. Try this value: `SameSite=None; Secure`
- Setting `Access-Control-Allow-Origin` header to `*` to ensure CORS
- Adding `sandbox` attribute to X-Frame tag. You may want to set `allow-scripts`, `allow-same-origin` and `allow-forms`

For example, `<iframe src="https://YourWebsite.com/"  sandbox="allow-scripts allow-same-origin allow-forms"></iframe>`

Can you please try this and let us know if this works for you?

**Comment by jayfinley** [comment]
Thanks 

Can you provide a sample config file that achieves this?

Im not sure Im applying the settings correctly.
