### ISSUE TITLE
Requestly App not opening for Indian Users with some ISPs (Excitel)

### ISSUE THREAD

**Issue by amudha-git** [requestly/customer-support#73]
https://app.requestly.io/rules/ not loading for me..
 It loads for other colleagues..!! Any way to identify the cause of this issue ?

**Comment by requestly-team** [comment]
Thanks @amudha-git  for opening the issue. We are looking into it.

**Comment by requestly-team** [comment]
Hey @amudha-git We are working with Firebase Support team over this. They have confirmed that Firebase is not working with certain ISPs in India only. 

![image](https://user-images.githubusercontent.com/35186614/98614329-32034c00-231e-11eb-991c-87c482d7b023.png)

Here is the official Firebase Status dashboard link which reflects the above statement - https://status.firebase.google.com/

**Comment by amudha-git** [comment]
Hi Requestly/Customer-Support,
 Thanks for your speedy response. Developers response time is greatly
appreciated!!

Thanks,
Amudhavigneshwaran

**Comment by requestly-team** [comment]
Hey @amudha-git 

We have made some changes on our end. It has started to work for some of our users. Can you please check at your end once?

**Comment by amudha-git** [comment]
Yeah it’s working fine. Thanks :)

**Comment by requestly-team** [comment]
Thanks @amudha-git for confirmation. Closing this issue.
