### ISSUE TITLE
Layout overlaps

### ISSUE THREAD

**Issue by alexey-danilin** [requestly/customer-support#74]
![image](https://user-images.githubusercontent.com/48120766/99958835-162a8c00-2d9b-11eb-8dbb-852e4d40e904.png)

**Comment by requestly-team** [comment]
Hi Aleksei,

Thanks for reporting this issue. Our team is working on it.

**Comment by requestly-team** [comment]
Hey Aleksei,
We've made some changes. Can you please clear the cache and try again?

**Comment by alexey-danilin** [comment]
> Hey Aleksei,
> We've made some changes. Can you please clear the cache and try again?

Cleared cache, cleared site data, relogged twice. Didn't help =( 

Btw it's on Chrome Version 87.0.4280.66 (Official Build) (64-bit) if it important.

+ Here some props if it important:
![image](https://user-images.githubusercontent.com/48120766/100067583-80006f80-2e47-11eb-8049-2a233227d41c.png)
![image](https://user-images.githubusercontent.com/48120766/100067654-98708a00-2e47-11eb-81c0-08d417d148e2.png)

**Comment by requestly-team** [comment]
Hi Aleksei!

Thanks for providing us the details. We have again updated the page.

Should be fixed by now.

Cheers!
Team Requestly

**Comment by alexey-danilin** [comment]
> Hi Aleksei!
> 
> Thanks for providing us the details. We have again updated the page.
> 
> Should be fixed by now.
> 
> Cheers!
> Team Requestly

Yep, it's good now =)

**Comment by requestly-team** [comment]
Hey @alexey-danilin Thank you so much for raising this issue and helping us get this fixed. You're awesome. Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
