### ISSUE TITLE
Add example how to use Modify using JavaScript feature.

### ISSUE THREAD

**Issue by Tyson1986** [requestly/customer-support#77]
I still don't understand how does it work. Documentation here (https://docs.requestly.io/using-rules/modify-ajax-response-rule) doesn't have any example. I assume that you override window.fetch, but even "return {}" doesn't work for me. Please provide an example of how can I modify a JSON in response.

**Comment by requestly-team** [comment]
@Tyson1986 As mentioned in the document, Modify response currently works only for AJAX requests sent via XMLHTTPRequest. Currently ajax requests sent by fetch is not supported. We are working on supporting response modification via fetch. It will be shipped soon.

**Comment by MonwF** [comment]
any plan to support modifying response header? ex: add cookie, location

**Comment by Tyson1986** [comment]
Fetch usage was an assumption. A few of my colleagues and I didn't succeed in the usage of this feature. Could you add any example in the documentation of how to use this feature?
