### ISSUE TITLE
a question of insert script rule

### ISSUE THREAD

**Issue by icditwang** [requestly/customer-support#78]
Is there any wrong in the configuration of this rule?Why it can't work?Please help me.
![image](https://user-images.githubusercontent.com/32595964/100329917-40818100-3009-11eb-9518-a228f9070f66.png)

**Comment by requestly-team** [comment]
@icditwang You don't need to insert jQuery and Underscore libraries because you are providing your own source of JS.

**Comment by icditwang** [comment]
I delete it and open {http://localhost:9110/statusi/api},it doesn't work also...,is there any log?

**Comment by requestly-team** [comment]
@icditwang This is because you have mentioned Host Contains `statusi`. In your localhost URL, `statusi` is not part of host. can you please change that condition to `URL` `Contains` `statusi` and try again?

**Comment by requestly-team** [comment]
@icditwang If this is resolved for you, can we please close this ticket?
