### ISSUE TITLE
incorrect count of files

### ISSUE THREAD

**Issue by davidtableau** [requestly/customer-support#81]
I only have 4 files in requestly yet I get the "updated required" error that says I've surpassed the limit of 5 files.

**Comment by requestly-team** [comment]
Hey @davidtableau 

Thanks for notifying this issue. We're looking into it and will resolve this by today.

**Comment by requestly-team** [comment]
Hi @davidtableau 

We have made some changes to our end. Feel free to reopen this issue in case the issue still persists or you have any question.
