### ISSUE TITLE
Modify or enable/disable rules programatically?

### ISSUE THREAD

**Issue by jseminck** [requestly/customer-support#82]
Hello, first of all thanks for the great tool. I have a question, is it possible to change the rules or enable/disable a rule programatically? I'm trying to optimise my workflow and it would be great if I could enable/disable rules or even add/remove certain rules from the command line.

Thanks,
Joachim

**Comment by requestly-team** [comment]
Hey @jseminck We are glad to know that you like Requestly. Currently, it is not possible to enable/disable a rule programatically. However, there is a Favourite Rule feature which will allow you to quickly toggle the rule without entering into Requestly UI. 

Please check out the demo here - https://twitter.com/RequestlyIO/status/1261724115318132736

Let us know if it solves your problem.

**Comment by requestly-team** [comment]
@jseminck Did you get a chance to look at the demo above? Does this solve your problem?

**Comment by jseminck** [comment]
Hello, thanks for the reply, and sorry for my late answer. I know about the favourite feature and I use it. But I have a need to enable/disable rules from the command line in order to speed up productivity even more. But if it's not possible then so be it. Thanks for the extension, it's a huge time-saver for me.
