### ISSUE TITLE
no conversion from https to file

### ISSUE THREAD

**Issue by serwap** [requestly/customer-support#84]
Hello, I would like to translate https links (on svn server) to corresponding URLs on my local drive (file:/), but it seems it is not working for conversion to file:/ urls.

**Comment by requestly-team** [comment]
Hi @serwap, Thanks for logging this issue. 

As of now, browsers do not allow an extension to redirect to file:// URLs. We will keep you posted here incase we find any workaround.

Closing this ticket for now. Feel free to reopen if you have any questions.
