### ISSUE TITLE
Size of JavaScript Program: Free vs Premium?

### ISSUE THREAD

**Issue by paul-bell** [requestly/customer-support#86]
In the free version there is a 1500 char limit on the modify response script.

If I subscribe to the premium version, is this constraint removed outright? If not, then is it at least raised to a larger number?

Please advise, thanks.

-Paul

**Comment by requestly-team** [comment]
Hey Paul,

Thanks for logging this issue. We actually maintain a buffer to prevent reaching the Chrome's Sync Storage limits, so switching to a premium plan wouldn't solve this.

Per our conversation over email, we have experimentally increased the limit to 6,000 characters. Also, you may want to change the storage type to local, in your Requestly account settings.

Closing this ticket for now. Feel free to reopen if you have any questions.
