### ISSUE TITLE
My Rules are Ignored

### ISSUE THREAD

**Issue by steverawlins-zebra** [requestly/customer-support#87]
I activated, for example, the Sample Rule to Block Social Media Sites.  Both the group and the specific rule are Enabled/Checked/ON

But I can still navigate to twitter.

What happened to the rule checking?
<img width="1243" alt="RequestlyBroken_1_rules" src="https://user-images.githubusercontent.com/52328771/104384833-c3966200-54f7-11eb-963d-294a3f94e9a5.png">

**Comment by requestly-team** [comment]
Hey @steverawlins-zebra,

Thanks for logging this issue. The sample rule "Block Social Media Sites" has a Request Source filter set to Main Document only. Can you please try editing the rule to remove this filter and see if it works?

Team Requestly

**Comment by steverawlins-zebra** [comment]
I removed that filter, saved, closed and tried and re-tried but still lets me go to twitter

**Comment by requestly-team** [comment]
Hey @steverawlins-zebra!

Greetings from Requestly support team. Actually, Twitter uses ServiceWorkers and loads the home page from Cache and hence the request for Twitter home page cannot be intercepted and hence cannot be redirected or blocked.

Here's an example of a similar request where a user tried to add a query parameter to twitter.com and we explained why this was not working. This is specific to chrome as Chrome Extensions don't play nicely with Service workers.

https://superuser.com/questions/1568685/how-to-add-a-parameter-to-a-website-twitter-using-chrome-extension/1571736#1571736

Here's what you can try instead

Create a script rule as mentioned in the above SuperUser.com answer and redirect the twitter to some other site like microlessons.xyz or stackoverflow.com or just facebook.com which is blocked by Requestly Block rule already.

**Comment by trizoza** [comment]
Hello there! The suggested solution above, did not work for twitter.com on Chrome version 88. twitter.com stays twitter.com. Any updates on this? Thanks!

**Comment by requestly-team** [comment]
Hey @trizoza 

We checked the script inside the sharedList, there was a condition set in the Script Rule code which works only when the URL contains 'status' word. I have changed the script and created a new sharedList for you here

https://app.requestly.io/rules/#sharedList/1612273132545-Add-parameter-to-Twitter

If you have Requestly Chrome Extension Installed, just click on above link and click on Import list. It should start working for you.

Here is the code present in the rule

```
const currentURL = window.location.href.toLowerCase();
// match your condition here
// Also check the param is not already added to avoid infinite redirects
if (currentURL.indexOf('status') > -1 && currentURL.indexOf('requestlyio') > -1 && currentURL.indexOf('s=21') === -1) {
  // Do the redirect here
  window.location.href = currentURL + '?s=21'
}
```

You will be able to change the rule once you import the list.

**Comment by steverawlins-zebra** [comment]
Requestly Rules, such as re-direct, are still ignored.  I tried your sample ideas (redir SO to microlessons):  did not do anything on Chrome, but on Firefox it worked as desired.
![RequestlyExtensionDetails_20210219](https://user-images.githubusercontent.com/52328771/108566121-7f9f3580-72cb-11eb-96d0-1258dcf377b6.png)

**Comment by requestly-team** [comment]
Hey @steverawlins-zebra Can you please create a sharedList for the rule you are trying! 

We can also jump on a call to help you resolve this issue.

**Comment by steverawlins-zebra** [comment]
My rule: https://app.requestly.io/rules/#sharedList/1613838117003-RedirectSO

**Comment by requestly-team** [comment]
@steverawlins-zebra Since these two issues are quite related and have redundant discussion, I am linking this to #90 and closing this one.
