### ISSUE TITLE
Is there any wat to add a wait timer to the redirect request?

### ISSUE THREAD

**Issue by duradara** [requestly/customer-support#88]
I want to do something like this:
  
Detect URL -> wait x seconds -> then redirect to destination

Sorry if you dont understand me

**Comment by requestly-team** [comment]
Hi @duradara,

As of now, it is not possible to add a delay in Redirect rule. 

However, if you want to setup a basic redirect on a web page, you can always create a Insert Script rule to redirect using Javascript.

`
       setTimeout(function(){
            window.location.href = 'https://YouNewURL.com';
         }, 5000);
`

Let us know if that works for you.

**Comment by Infin8y** [comment]
Hey @duradara 

This is now possible with Requestly Chrome Extension. You can use `Delay Request Rule` to introduce a delay to a particular request. Check this out - https://requestly.io/blog/2021/07/02/adding-delay-to-network-requests/

Feel free to let us know if you try this out and face any issues. We are just a reply away here.
