### ISSUE TITLE
Script runs on Firefox, but not on Chrome

### ISSUE THREAD

**Issue by drsood** [requestly/customer-support#89]
Hi,
I wrote a java script code, which works great in Firefox, however chrome doesn't seem to run it at all.

`var xhr = new XMLHttpRequest();
 var url = "https://xyz.com";
 var data = "user=1234&pass=1234";
 xhr.open("POST", url, true);
 xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
 xhr.onreadystatechange = function () {
     if (xhr.readyState == 4 && xhr.status == 200) {
         //console.log($1);
       location.reload();
     }
};
xhr.send(data);`

**Comment by requestly-team** [comment]
Hey @drsood 

Can you please share the exact rule which you are using? Also need to know the URL on which you are trying to run this script.

You can follow this guide to create a sharedList for your rule(s) - https://docs.requestly.io/managing-rules/sharing
