### ISSUE TITLE
My rules don't work after the latest update.

### ISSUE THREAD

**Issue by tlckfeks** [requestly/customer-support#90]
<img src="https://i.ibb.co/VH5PdXj/aaaaaaaaaaaa.png" alt="aaaaaaaaaaaa" border="0">

My rules don't work after the latest update.

**Comment by requestly-team** [comment]
Hey @tlckfeks We haven't made any new release in last 3-4 months related to our extension. Can you please check the following

1. If your Requestly extension is enabled or not? Requestly Icon turns Grey when not activated.
2. Can you please share the screenshot of chrome://extensions page. It might be possible that some other extension has started to conflict with Requestly on this particular URL
3. Can you please create a simple Rule like
URL Contains stackoverflow.com
Destination https://microlessons.xyz/

**Comment by steverawlins-zebra** [comment]
Requestly no longer works on Chrome.  I have tried several times now, from scratch (Redirect and Cancel rules) and working with the Sample Rules.  When I tried on Firefox, it worked.

I can no longer find your Sample Rules, but even the most basic rule fails to fire in Chrome.

Here is screenshot from my Chrome Extension:
![RequestlyExtensionDetails_20210219](https://user-images.githubusercontent.com/52328771/108565940-2f27d800-72cb-11eb-9208-4fdba47f84be.png)

**Comment by requestly-team** [comment]
@steverawlins-zebra Can we jump on a call to troubleshoot the issue for you? There are a couple of things which you want to try at your end

1. Right Click on Requestly Extension Icon and see if your extension is enabled or not. Here is the screenshot
![image](https://user-images.githubusercontent.com/35186614/108583433-68118c80-735f-11eb-8352-cfecdd4fe9bd.png)

It is possible that by mistake you might have deactivated the extension. Here is the documentation of deactivate feature - https://docs.requestly.io/uninstall/deactivate

2. Check what is the color of the icon. If it is grey, then it is just in deactivated mode and you can quickly enable by right click and do activate.

3. Check if the group under which rule is present is active or not. 

If None of these things help, I'd be happy to jump on a call and help you out.

**Comment by steverawlins-zebra** [comment]
Here is my attempt, sent as a Shared List of Rules:
https://app.requestly.io/rules/#sharedList/1613838117003-RedirectSO

My Requestly Extension is active and I have played with Extension Manager (so I understand what you mean).   I did not accidentally deactivate.

**Comment by requestly-team** [comment]
Hey @steverawlins-zebra 

It looks like the container (or Group) in which this rule lies, is inactive. Here is the documentation about [Grouping Rules in Requestly as per use case](https://docs.requestly.io/managing-rules/groups) so that entire set of rules can be enabled or disabled together.

![Screenshot 2021-02-22 at 3 09 05 PM](https://user-images.githubusercontent.com/35186614/108690197-1401d600-7520-11eb-962f-9301e6a80f53.png)

Can you please activate the Group which contains this rule and try again at your end.

**Comment by steverawlins-zebra** [comment]
Thanks, requestly-team.  Clearly, I did not understand Groups!  I activated my Group "StevesAttempts" and now the redirect to microlessons works fine, but I am back to the original problem:  the Twitter block still does nothing.   Is it a limitation on Chrome?
https://app.requestly.io/rules/#sharedList/1614015722248-SteveSezBlockTwitter

**Comment by requestly-team** [comment]
@steverawlins-zebra Thanks for confirming!

Twitter uses ServiceWorkers to load their home page and hence Chrome Extensions are not able to modify/redirect/block Twitter directly. But here is another approach

https://app.requestly.io/rules/#sharedList/1614056856749-redirect-twitter-to-microlessons

Just Open the rule above and Import this and it will take you to microlessons when you open twitter.com. Let us know if it works.

**Comment by steverawlins-zebra** [comment]
Thank you!  The `window.location.href` did the trick; Twitter.com now re-directs to microlessons, as desired.  Nice job, good Extension; I will keep using it.

**Comment by requestly-team** [comment]
Hey @steverawlins-zebra Thanks for confirming, this worked for you. Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en

**Comment by steverawlins-zebra** [comment]
Done.  Nice work on this plug-in.  Thank you.
