### ISSUE TITLE
How to replace query parameter in Google Analytics call?

### ISSUE THREAD

**Issue by requestly-team** [requestly/customer-support#92]
![image](https://user-images.githubusercontent.com/35186614/107203161-155fd880-6a21-11eb-86e6-d72d9fed272b.png)

**Comment by requestly-team** [comment]
Hey, You can use Query Params Rule to modify the value of a query parameter. Here is the documentation for it - https://medium.com/requestly-docs/introducing-query-param-rule-d152b28eec08

Here is what is mentioned in FAQ 1 which should help you out.

```
Q1. If I add a parameter by QueryParam rule and the same parameter already exists in the given url, will Requestly overwrite the parameter value ?
Ans: Yes, Requestly will overwrite the value present in the url to the value given in the rule. For example:
Rule Definition:
Url Contains example.com
Add Param “a” Value “200”
When Requestly gets above query param rule definition and the request url is http://www.example.com?a=100, then it will change the param value to 200 as per the rule and the new url will be http://www.example.com?a=200
```

**Comment by dimitriDries** [comment]
Thanks! I seem to have got it to work.

Best regards.

**Comment by requestly-team** [comment]
Thanks @dimitriDries Closing this ticket! Can you please rate us on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en
