### ISSUE TITLE
A file can't be deleted

### ISSUE THREAD

**Issue by erkesado** [requestly/customer-support#96]
Hello,

After uploading 5 files, I realized that I reached my free account limit and can't edit any of 5 files.
Then, I tried to restore my free account by deleting one of my 5 files. But I can't delete any of them.
Can I test Requestly further by deleting a file and restoring my free account?
After a thorough test, I'll make a decision of buying it.

Thanks in advance,
Erdenebat Oyungerel

**Comment by erkesado** [comment]
Hello @requestly-team,

I signed in from different computer and deleted a file successfully.
So my issue is resolved.

Thanks for your support.

**Comment by requestly-team** [comment]
Thanks @erkesado Please share your feedback with us and let us know how can we improve. You can drop us an email at contact at requestly dot io
