### ISSUE TITLE
How to Replace Version Numbers in URLs?

### ISSUE THREAD

**Issue by requestly-team** [requestly/customer-support#98]
![image](https://user-images.githubusercontent.com/35186614/110419215-e2ac0d00-80be-11eb-9183-40fdb8406d91.png)

**Comment by requestly-team** [comment]
Hey Shannon, This is easily possible using Replace Rule and yes Replace Rule supports regex. Here's an example of Regex in Replace Rule - https://www.youtube.com/watch?v=Pwgh4_Jk1M8&ab_channel=RequestlyExtension

If you can provide the Example Requestly URL and the destination URL, we will be able to help you out better.

**Comment by shannonhochkins** [comment]
Thanks!

**Comment by requestly-team** [comment]
@shannonhochkins Please keep us posted when your rule is made. Otherwise we'd be super glad to help you out once you share an example of the URLs on which you want to setup a redirect.

**Comment by requestly-team** [comment]
@shannonhochkins Did the video work for you? Do you need more help?
