### ISSUE TITLE
Can't download desktop app

### ISSUE THREAD

**Issue by mavr1982** [requestly/customer-support#99]
Link to download desktop app does not work.
https://requestly.io/desktop/

**Comment by requestly-team** [comment]
Hey @mavr1982, thanks for logging this issue.

Please use this direct link while we update the page: https://files.requestly.io/mac-app

**Comment by requestly-team** [comment]
We have also updated the link on the website.

Closing this ticket for now. Feel free to reopen if you have any questions.
